"""initial

Revision ID: 001
Revises: 
Create Date: 2024-03-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_incidencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'critica', name='prioridadenum'), nullable=False),
    sa.Column('tiempo_resolucion_horas', sa.Integer(), nullable=False),
    sa.Column('requiere_servicio_externo', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estadotipoenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_incidencia_codigo'), 'tipos_incidencia', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_incidencia_id'), 'tipos_incidencia', ['id'], unique=False)
    
    op.create_table('reclamos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo_incidencia_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'en_proceso', 'resuelto', 'cerrado', 'rechazado', name='estadoreclamoenum'), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'critica', name='prioridadenum'), nullable=False),
    sa.Column('nombre_reportante', sa.String(length=200), nullable=False),
    sa.Column('contacto_reportante', sa.String(length=200), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('asignado_a', sa.String(length=200), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tipo_incidencia_id'], ['tipos_incidencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclamos_codigo'), 'reclamos', ['codigo'], unique=True)
    op.create_index(op.f('ix_reclamos_id'), 'reclamos', ['id'], unique=False)
    
    op.create_table('historial_estados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reclamo_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('cambiado_por', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reclamo_id'], ['reclamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_reclamos_id'), table_name='reclamos')
    op.drop_index(op.f('ix_reclamos_codigo'), table_name='reclamos')
    op.drop_table('reclamos')
    op.drop_index(op.f('ix_tipos_incidencia_id'), table_name='tipos_incidencia')
    op.drop_index(op.f('ix_tipos_incidencia_codigo'), table_name='tipos_incidencia')
    op.drop_table('tipos_incidencia')
    op.execute("DROP TYPE estadotipoenum")
    op.execute("DROP TYPE prioridadenum")
    op.execute("DROP TYPE estadoreclamoenum")
    # ### end Alembic commands ###
