"""unificar_idioma_fechas

Revision ID: cd8081afed24
Revises: 001
Create Date: 2026-03-19 15:00:57.485293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd8081afed24'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamos', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('reclamos', 'deleted_at')
    op.add_column('tipos_incidencia', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tipos_incidencia', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tipos_incidencia', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tipos_incidencia', 'created_at')
    op.drop_column('tipos_incidencia', 'updated_at')
    op.drop_column('tipos_incidencia', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_incidencia', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tipos_incidencia', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tipos_incidencia', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('tipos_incidencia', 'fecha_eliminacion')
    op.drop_column('tipos_incidencia', 'fecha_actualizacion')
    op.drop_column('tipos_incidencia', 'fecha_creacion')
    op.add_column('reclamos', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('reclamos', 'fecha_eliminacion')
    # ### end Alembic commands ###
